### ISSUE TITLE
Add examples for deploying to various cloud hosting providers

### ISSUE THREAD

**Issue by amellnik** [amellnik/Joseki.jl#20]
This is a fairly common sticking point for users who haven't used them before.  It's probably best to focus on the ones which have free tiers that can be used.

**Comment by amellnik** [comment]
I'm also planning on adding an example for Heroku using a container.  @milesfrain would you be interested in adding your buildpack example here?  I'm also glad to make the PR and give you the credit if that would be easier.

**Comment by milesfrain** [comment]
I'm happy to add the buildpack example, but the workflow is smoothest if the example exists as a standalone git repo.
I think the ideal arrangement is to put all these related repos under a Joseki org, but feel free to incorporate the buildpack example however you wish.

**Comment by amellnik** [comment]
GCP and Heroku examples added to the new Joseki org: https://github.com/Joseki-jl

Closing this for now, will add AWS later.
