### ISSUE TITLE
Errors on Kubernetes

### ISSUE THREAD

**Issue by wadehenning** [amellnik/Joseki.jl#7]
I am trying to get your great repo to run on Kubernetes following this simple tutorial:  
https://cloud.google.com/kubernetes-engine/docs/tutorials/hello-app

When I try and run the container, I get the following error:
ERROR: LoadError: LoadError: LoadError: UndefVarError: AbstractDict not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
while loading /packages/Joseki/src/utilities.jl, in expression starting on line 521
while loading /packages/Joseki/src/Joseki.jl, in expression starting on line 6
while loading /server.jl, in expression starting on line 1

Any ideas on how to fix this?  
I also noticed that you have passed the Julia v1.0 tests.  Are you planning on updating the example?
Thank you

**Comment by amellnik** [comment]
Hi Wade,

I'm glad to hear that you're trying out the package!  It looks like AbstractDict only exists on 0.7 and 1.0, so I need to update the package and Readme to indicate that it will no longer work on 0.6.  I'll also update the included docker container.  Thanks,

Alex

**Comment by amellnik** [comment]
This should be fixed via https://github.com/amellnik/Joseki.jl/commit/31b71cb1508a70c3b33db9590db596645660cf65 and Joseki now requires Julia 1.0 explicitly.  Let me know if you run into any other issues!

**Comment by wadehenning** [comment]
Thank you very much.  This is an important package; I have spent a lot of time trying to understand this issue, and your package is the only resource I have been able to understand.

**Comment by wadehenning** [comment]
Hi Alex,
I was able to successfully build your package, so great job.  This question is not an 'issue' with your package, so I didn't want to post it on your repo page.  But would you be willing to help me POST a request to the binomial function in the service I have going?  I have never use a REST API before and am having trouble getting a successful response.  I have been trying it using POSTMAN.  
The External ID of my service is: 35.238.222.54The API Key is: AIzaSyDT-BssPUeGbc1NdkmrTOynJbkq2GjaDvAPORT: 80:32763/TCP

I understand that this is out of your scope and may be too much nuisance for you, and I appreciate your attention. 
All the Best,
Wade
    On Friday, September 14, 2018, 5:02:30 PM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
This should be fixed via 31b71cb and Joseki now requires Julia 1.0 explicitly. Let me know if you run into any other issues!

**Comment by amellnik** [comment]
I would be glad to take a look, but I don't have a chance until ~6 this evening pacific time.  Is the GET endpoint working for you, and if so, how are you testing it?

**Comment by wadehenning** [comment]
Any time is great- thank you.    I haven't tried GET.  POST seems like a nice format for when I move to making requests from Javascript so started here.  
    On Monday, September 17, 2018, 11:55:41 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
I would be glad to take a look, but I don't have a chance until ~6 this evening pacific time. Is the GET endpoint working for you, and if so, how are you testing it?

**Comment by wadehenning** [comment]
Once again,  this is exactly the process I followed Deploying a containerized web application | Kubernetes Engine Tutorials | Google Cloud.

| 
| 
|  | 
Deploying a containerized web application | Kubernetes Engine Tutorial...


 |

 |

 |



I forked your Joseki.jl repo and renamed it JuliaServer.  Then I cloned my JuliaServer repo and went through the above process.  

    On Monday, September 17, 2018, 12:10:24 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Any time is great- thank you.    I haven't tried GET.  POST seems like a nice format for when I move to making requests from Javascript so started here.  
    On Monday, September 17, 2018, 11:55:41 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
I would be glad to take a look, but I don't have a chance until ~6 this evening pacific time. Is the GET endpoint working for you, and if so, how are you testing it?

**Comment by wadehenning** [comment]
I think in addition to the 'Deploying a container..' tutorial, I needed to also configure endpoints.  Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints with OpenAPI | Google Cloud


| 
| 
|  | 
Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints ...


 |

 |

 |




    On Monday, September 17, 2018, 12:23:34 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Once again,  this is exactly the process I followed Deploying a containerized web application | Kubernetes Engine Tutorials | Google Cloud.

| 
| 
|  | 
Deploying a containerized web application | Kubernetes Engine Tutorial...


 |

 |

 |



I forked your Joseki.jl repo and renamed it JuliaServer.  Then I cloned my JuliaServer repo and went through the above process.  

    On Monday, September 17, 2018, 12:10:24 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Any time is great- thank you.    I haven't tried GET.  POST seems like a nice format for when I move to making requests from Javascript so started here.  
    On Monday, September 17, 2018, 11:55:41 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
I would be glad to take a look, but I don't have a chance until ~6 this evening pacific time. Is the GET endpoint working for you, and if so, how are you testing it?

**Comment by wadehenning** [comment]
Hell I don't know.  Here's the current endpoints of the service:


    On Monday, September 17, 2018, 1:12:46 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  I think in addition to the 'Deploying a container..' tutorial, I needed to also configure endpoints.  Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints with OpenAPI | Google Cloud


| 
| 
|  | 
Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints ...


 |

 |

 |




    On Monday, September 17, 2018, 12:23:34 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Once again,  this is exactly the process I followed Deploying a containerized web application | Kubernetes Engine Tutorials | Google Cloud.

| 
| 
|  | 
Deploying a containerized web application | Kubernetes Engine Tutorial...


 |

 |

 |



I forked your Joseki.jl repo and renamed it JuliaServer.  Then I cloned my JuliaServer repo and went through the above process.  

    On Monday, September 17, 2018, 12:10:24 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Any time is great- thank you.    I haven't tried GET.  POST seems like a nice format for when I move to making requests from Javascript so started here.  
    On Monday, September 17, 2018, 11:55:41 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
I would be glad to take a look, but I don't have a chance until ~6 this evening pacific time. Is the GET endpoint working for you, and if so, how are you testing it?

**Comment by wadehenning** [comment]
sorry- those are INTERNAL endpoints for the pods
    On Monday, September 17, 2018, 1:21:49 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Hell I don't know.  Here's the current endpoints of the service:


    On Monday, September 17, 2018, 1:12:46 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  I think in addition to the 'Deploying a container..' tutorial, I needed to also configure endpoints.  Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints with OpenAPI | Google Cloud


| 
| 
|  | 
Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints ...


 |

 |

 |




    On Monday, September 17, 2018, 12:23:34 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Once again,  this is exactly the process I followed Deploying a containerized web application | Kubernetes Engine Tutorials | Google Cloud.

| 
| 
|  | 
Deploying a containerized web application | Kubernetes Engine Tutorial...


 |

 |

 |



I forked your Joseki.jl repo and renamed it JuliaServer.  Then I cloned my JuliaServer repo and went through the above process.  

    On Monday, September 17, 2018, 12:10:24 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Any time is great- thank you.    I haven't tried GET.  POST seems like a nice format for when I move to making requests from Javascript so started here.  
    On Monday, September 17, 2018, 11:55:41 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
I would be glad to take a look, but I don't have a chance until ~6 this evening pacific time. Is the GET endpoint working for you, and if so, how are you testing it?

**Comment by wadehenning** [comment]
And I don't think this is required- optional package.  Still trying to figure out if there is more I need to do.
    On Monday, September 17, 2018, 1:12:46 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  I think in addition to the 'Deploying a container..' tutorial, I needed to also configure endpoints.  Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints with OpenAPI | Google Cloud


| 
| 
|  | 
Getting Started with Endpoints on Kubernetes Engine | Cloud Endpoints ...


 |

 |

 |




    On Monday, September 17, 2018, 12:23:34 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Once again,  this is exactly the process I followed Deploying a containerized web application | Kubernetes Engine Tutorials | Google Cloud.

| 
| 
|  | 
Deploying a containerized web application | Kubernetes Engine Tutorial...


 |

 |

 |



I forked your Joseki.jl repo and renamed it JuliaServer.  Then I cloned my JuliaServer repo and went through the above process.  

    On Monday, September 17, 2018, 12:10:24 PM EDT, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Any time is great- thank you.    I haven't tried GET.  POST seems like a nice format for when I move to making requests from Javascript so started here.  
    On Monday, September 17, 2018, 11:55:41 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
I would be glad to take a look, but I don't have a chance until ~6 this evening pacific time. Is the GET endpoint working for you, and if so, how are you testing it?

**Comment by amellnik** [comment]
Hi Wade,

I finally had some time this afternoon, and was able to deploy the default Joseki docker image to Google Cloud: http://35.197.67.210/pow/?x=2&y=3

The only thing I needed to change in some of the commands was the port that's being exposed -- the Joseki example exposes port 8000 rather than 8080 as in the GCloud instructions.  If you still are not able to get this working let me know -- the easiest way to contact me is via the Julia developers Slack.  Best -A

**Comment by wadehenning** [comment]
Very good!  I'll check it out later today.
    On Thursday, September 20, 2018, 12:57:56 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
Hi Wade,

I finally had some time this afternoon, and was able to deploy the default Joseki docker image to Google Cloud: http://35.197.67.210/pow/?x=2&y=3

The only thing I needed to change in some of the commands was the port that's being exposed -- the Joseki example exposes port 8000 rather than 8080 as in the GCloud instructions.  If you still are not able to get this working let me know -- the easiest way to contact me is via the Julia developers Slack. Best -A

**Comment by wadehenning** [comment]
It's a great day to be alive.  I will use Slack in the future.  Thank you.  
http://35.238.222.54/pow/?x=2&y=3
    On Thursday, September 20, 2018, 12:57:56 AM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
Hi Wade,

I finally had some time this afternoon, and was able to deploy the default Joseki docker image to Google Cloud: http://35.197.67.210/pow/?x=2&y=3

The only thing I needed to change in some of the commands was the port that's being exposed -- the Joseki example exposes port 8000 rather than 8080 as in the GCloud instructions.  If you still are not able to get this working let me know -- the easiest way to contact me is via the Julia developers Slack. Best -A
