### ISSUE TITLE
Enable CORS?

### ISSUE THREAD

**Issue by wadehenning** [amellnik/Joseki.jl#8]
I am using the javascritp ```fetch``` api to call your basic server test code.  Works perfectly with the vanilla ```GET```.   I am having the trouble when I move to a more complicated ```POST``` setup that is seems similar to [this discussion.](https://stackoverflow.com/questions/36878255/allow-access-control-allow-origin-header-using-html5-fetch-api)  Do you have advice on how to resolve this?  Thank you.

 My error:
```
Access to fetch at 'http://35.238.222.54/bin' from origin 'http://localhost:3000' has been blocked by CORS 
policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' 
header is present on the requested resource. If an opaque response serves your needs, set the request's 
mode to 'no-cors' to fetch the resource with CORS disabled.
```
My code:
```
callpost(){
    postData('http://xx.xxx.xxx.xx/bin', {"n": 4, "k": 3})
      .then(data => console.log(JSON.stringify(data))) // JSON-string from `response.json()` call
      .catch(error => console.error(error));
  }

export function postData(url = ``, data = {}) {
  // Default options are marked with *
    return fetch(url, {
        method: "POST", // *GET, POST, PUT, DELETE, etc.
        //mode: "no-cors", // no-cors, cors, *same-origin
        cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached   
        headers: {
            "Content-Type": "application/json; charset=utf-8",     
        },   
        body: JSON.stringify(data), // body data type must match "Content-Type" header
    })    
    .then(response => response.json()); // parses response to JSON
}

```

**Comment by amellnik** [comment]
I think you might need to add an endpoint which accepts OPTIONS requests -- before sending POST requests browsers make pre-flight OPTIONS requests to see if it's OK to make POST requests and maybe that's also happening automatically here?  There may also be a header you need to set on the client side -- I'll check one of my projects where I've done this on Monday.

**Comment by wadehenning** [comment]
Hi @amellnik .  Have you had time to look at this yet?    This is my first exposure to these ideas and I appreciate your experience.

When you state above, ```I think you might need to add an endpoint which accepts OPTIONS requests```, do you mean in Kubernetes or in the Julia Docker code? 

 [This discussion](https://github.com/kubernetes/ingress-nginx/issues/2535) encountered the CORS problem using  Kubernetes by configuring their nginx server.  Is there a similar approach we can take with our Julia server?

[Here](https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors), the author suggests a general solution by rerouting through Heroku.  That seems a little hacky, but I don't know.  What do you think?

**Comment by amellnik** [comment]
On the server I am using the default middleware item `Joseki.add_cors!` and I have an endpoint that looks like `(req -> req.response, "OPTIONS", "*")`.   I don't think you should need to do anything beyond this.  On the client the only header that I set is `Content-Type`.

**Comment by wadehenning** [comment]
So, if I understand correctly, the only change I need to make is to change the endpoints like below?  Because the Joseki.jl server I am using has the middleware item ```Joseki.add_cors!``` already set up by default and my above header is already ok.

I don’t think I asked this correctly- do I have to change anything to enable Joseki.add_cors!


```
endpoints = [
    (pow, "GET", "/pow"),
    (bin, "POST", "/bin"),
(req -> req.response, "OPTIONS", "*")
]
```

**Comment by wadehenning** [comment]
Hi Alex,
Your Julia server has been working well for me, however, something strange is happening today with your example code.  I am doing some debugging in my stack so I went back to your original code as a clean starting point.  I have it running on Google Compute Engine.
I am able to reach the service, but with a strange error.  Here is my IP call and result:
http://35.199.187.67/pow/?x=2\&y=3

{"error": true, "message": "ArgumentError(\"cannot parse \"2\\\\\" as Float32\")"}

    On Friday, November 2, 2018, 01:25:25 PM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
On the server I am using the default middleware item Joseki.add_cors! and I have an endpoint that looks like (req -> req.response, "OPTIONS", "*"). I don't think you should need to do anything beyond this. On the client the only header that I set is Content-Type.

**Comment by wadehenning** [comment]
Sorry Alex.  You know how sometimes you are only able to figure it out only AFTER you ask the question (and walk away from it for a bit)?  Bad syntax on my part.http://35.199.187.67/pow/?x=2&y=3

{"error": false, "result": 8.0}

    On Tuesday, February 18, 2020, 12:30:43 PM EST, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Hi Alex,
Your Julia server has been working well for me, however, something strange is happening today with your example code.  I am doing some debugging in my stack so I went back to your original code as a clean starting point.  I have it running on Google Compute Engine.
I am able to reach the service, but with a strange error.  Here is my IP call and result:
http://35.199.187.67/pow/?x=2\&y=3

{"error": true, "message": "ArgumentError(\"cannot parse \"2\\\\\" as Float32\")"}

    On Friday, November 2, 2018, 01:25:25 PM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
On the server I am using the default middleware item Joseki.add_cors! and I have an endpoint that looks like (req -> req.response, "OPTIONS", "*"). I don't think you should need to do anything beyond this. On the client the only header that I set is Content-Type.

**Comment by wadehenning** [comment]
Alex,
How do I modify a function to return a matrix or array instead of a scalar value.  For example, suppose we change the 'pow' function to 'returnmx'.  Or I might need to return multiple array objects.

| function returnmx(req::HTTP.Request) |
|  |  j = HTTP.queryparams(HTTP.URI(req.target)) |
|  |  has_all_required_keys(["x", "y"], j) || return error_responder(req, "You need to specify values for x and y!") |
|  |  # Try to parse the values as numbers. If there's an error here the generic |
|  |  # error handler will deal with it. |
|  |  x = parse(Float32, j["x"]) |
|  |  y = parse(Float32, j["y"]) A = rand(x,y) |
|  |  json_responder(req, A) |
|  | end |



    On Friday, November 2, 2018, 01:25:25 PM EDT, Alex Mellnik <notifications@github.com> wrote:  
 
 
On the server I am using the default middleware item Joseki.add_cors! and I have an endpoint that looks like (req -> req.response, "OPTIONS", "*"). I don't think you should need to do anything beyond this. On the client the only header that I set is Content-Type.

**Comment by amellnik** [comment]
That should work as written.  [Under the hood](https://github.com/Joseki-jl/Joseki.jl/blob/master/src/responders.jl#L19) Joseki uses JSON.json to serialize objects and it should work happily on matrices, (which are represented as arrays of arrays in json).

**Comment by wadehenning** [comment]
Thank you for the reply on this.  Should the result successfully output to the browser?http://35.199.181.217/returnmx/?x=2&y=3
{"error": true, "message": "MethodError(rand, (2.0f0, 3.0f0), 0x000000000000689b)"}
for comparisonhttp://35.199.181.217/pow/?x=2&y=3
{"error": false, "result": 8.0}

    On Wednesday, February 26, 2020, 12:36:09 AM EST, Alex Mellnik <notifications@github.com> wrote:  
 
 
That should work as written. Under the hood Joseki uses JSON.json to serialize objects and it should work happily on matrices, (which are represented as arrays of arrays in json).

**Comment by wadehenning** [comment]
OH!  It's because it's casting the incoming parameter values to a float!  Check and thanks.
    On Wednesday, February 26, 2020, 09:37:36 AM EST, Wade Henning <wadehenning@yahoo.com> wrote:  
 
  Thank you for the reply on this.  Should the result successfully output to the browser?http://35.199.181.217/returnmx/?x=2&y=3
{"error": true, "message": "MethodError(rand, (2.0f0, 3.0f0), 0x000000000000689b)"}
for comparisonhttp://35.199.181.217/pow/?x=2&y=3
{"error": false, "result": 8.0}

    On Wednesday, February 26, 2020, 12:36:09 AM EST, Alex Mellnik <notifications@github.com> wrote:  
 
 
That should work as written. Under the hood Joseki uses JSON.json to serialize objects and it should work happily on matrices, (which are represented as arrays of arrays in json).
